### ISSUE TITLE
Release_8.0: Whoops when clicking on "Save Order" in Settings

### ISSUE THREAD

**Issue by samuelinniger** [DatabayAG/TestOverview#7]
Whoops when clicking on the button "Save Order" (when no Test is allocated)

<img width="1158" alt="grafik" src="https://github.com/user-attachments/assets/ec0930f8-f5b4-4dd8-ae61-2431f19fc032">

<img width="1276" alt="grafik" src="https://github.com/user-attachments/assets/bbf77ff4-5e00-4cb7-a807-68dfa0cb2418">

Plugin Version 8.0.0.
ILIAS v8.14 2024-08-13

**Comment by mbecker-databay** [comment]
Fix in git
