### ISSUE TITLE
Release_8.0: lang_var issue, when clicking on "Add tests from course"

### ISSUE THREAD

**Issue by samuelinniger** [DatabayAG/TestOverview#8]
When clicking the button "Add tests from Course" in the pluginsettigs, a green notification appears (Bug), even though no tests were selected.

Lang_var / traduction is missing for both german and english

<img width="1169" alt="grafik" src="https://github.com/user-attachments/assets/86bead6d-e34b-4d14-9b83-55a0c5057411">

<img width="587" alt="grafik" src="https://github.com/user-attachments/assets/1ba540db-21d5-45d5-883d-cb0d6ee01d78">

Plugin Version 8.0.0.
ILIAS v8.14 2024-08-13

**Comment by mbecker-databay** [comment]
Fix in git

**Comment by samuelinniger** [comment]
Thx, but 

-rep_robj_xtov_rep_robj_xtov_tests_updated_success-

also seems to have an issue/missing text (both german and english)

<img width="554" alt="grafik" src="https://github.com/user-attachments/assets/362c2db6-b311-49b8-a138-3692ab0d38c3">
